# mypetset.yml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: a-mongo
  labels:
    name: a-mongo
    tier: database
    type: mongo
spec:
  ports:
  - port: 27017
    name: mongo
  type: NodePort
  selector:
    tier: database
    name: a-mongo
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: a-mongo
spec:
  serviceName: "a-mongo"
  replicas: 3
  template:
    metadata:
      labels:
        name: a-mongo
        tier: database
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: registry.access.redhat.com/rhscl/mongodb-32-rhel7:latest
        command:
          - mongod
          - "--replSet"
          - rs0
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          name: mongo
        resources:
          requests:
            cpu: "0.1m"
            memory: "64Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
         - name: mongodb-data
           mountPath: /var/lib/mongodb/data
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: solidfire-gold
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
