apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2016-03-18T19:55:26Z
  labels:
    template: mysql-persistent-template
  name: mysql-nfs
  namespace: mysql-static-nfsvol
  resourceVersion: "38707"
  selfLink: /oapi/v1/namespaces/mysql-static-nfsvol/deploymentconfigs/mysql-nfs
  uid: 5b9fb91e-ed43-11e5-9ef1-080027129698
spec:
  replicas: 1
  selector:
    name: mysql-nfs
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mysql-nfs
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          value: gregh
        - name: MYSQL_PASSWORD
          value: redhat
        - name: MYSQL_DATABASE
          value: sampledb
        image: registry.access.redhat.com/rhscl/mysql-56-rhel7:latest
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: mysql-nfs-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-nfs-data
        nfs:
          path: /mnt/openshift/pv0005
          server: 127.0.0.1
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - mysql
      from:
        kind: ImageStreamTag
        name: mysql:latest
        namespace: openshift
      lastTriggeredImage: registry.access.redhat.com/rhscl/mysql-56-rhel7:latest
    type: ImageChange
  - type: ConfigChange
status:
  details:
    causes:
    - type: ConfigChange
  latestVersion: 2
